name: SonarQube and Jenkins Trigger

on:
  push:
    branches:
      - main

jobs:
  sonar_analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-*.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin"
          sonar-scanner \
            -Dsonar.projectKey=Shopping_React_website \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://843b-49-156-93-193.ngrok-free.app \
            -Dsonar.login=$SONAR_TOKEN

  trigger_jenkins:
    name: Trigger Jenkins Build
    needs: sonar_analysis
    runs-on: ubuntu-latest

    steps:
      - name: Call Jenkins job via API
        run: |
          curl -X POST http://localhost:8080/job/shopping-react-build/build \
          --user lokesh:${{ secrets.JENKINS_TOKEN }}

